version: "3.9"

services:
  discovery:
    build:
      context: .
      dockerfile: discovery_server/Dockerfile.server
    container_name: discovery-server
    ports:
      - "8000:8000"

  peer1:
    build:
      context: .
      dockerfile: Dockerfile.peer
    container_name: peer1
    stdin_open: true
    tty: true
    environment:
      - DISCOVERY_URL=http://discovery:8000

  peer2:
    build:
      context: .
      dockerfile: Dockerfile.peer
    container_name: peer2
    stdin_open: true
    tty: true
    environment:
      - DISCOVERY_URL=http://discovery:8000
