FROM python:3.12.10-slim-bookworm

WORKDIR /app

COPY ./peer_client.py /app/peer_client.py
COPY ./requirements.txt /app/requirements.txt

RUN pip install --no-cache-dir -r /app/requirements.txt

# Keep interactive mode for user input
ENTRYPOINT ["python", "/app/peer_client.py"]
